In [1]:
import torch

In [8]:
x = torch.Tensor([5,3]) 
y = torch.Tensor([2,1]) 

In [7]:
print(x)

tensor([5., 3.])


In [9]:
print(x*y)

tensor([10.,  3.])


In [10]:
print(x+y)

tensor([7., 4.])


In [11]:
z = torch.zeros([3,4]) # call zeros function and assign zero value to 3 rows and 4 columns (size)

In [12]:
print(z)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [13]:
print(x.shape)

torch.Size([2])


In [14]:
print(z.shape)

torch.Size([3, 4])


In [15]:
a = torch.ones([4,3])
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [17]:
b = torch.rand([3,5]) # random values for the 3,5 size
print(b)
# Returns a tensor filled with random numbers from a uniform 
# distribution on the interval [0, 1)

tensor([[0.0564, 0.3841, 0.7242, 0.1517, 0.1081],
        [0.1963, 0.5585, 0.8673, 0.1446, 0.9613],
        [0.7366, 0.7013, 0.8161, 0.2294, 0.2975]])


In [18]:
# reshape the above tensor
b.view([5,3])

tensor([[0.0564, 0.3841, 0.7242],
        [0.1517, 0.1081, 0.1963],
        [0.5585, 0.8673, 0.1446],
        [0.9613, 0.7366, 0.7013],
        [0.8161, 0.2294, 0.2975]])

In [19]:
# reshape the above tensor
b.view([1,15])

tensor([[0.0564, 0.3841, 0.7242, 0.1517, 0.1081, 0.1963, 0.5585, 0.8673, 0.1446,
         0.9613, 0.7366, 0.7013, 0.8161, 0.2294, 0.2975]])